// cocinar-data.js — mock recipe + timer minutes
window.RECETA_COCINAR = {
  id: 'r1',
  nombre: 'Milanesas con puré',
  porciones: 4,
  cocineros: [{ id: 'jp', nombre: 'JP', color: '#8a4a2f' }],
  riesgos: 'Atención con el aceite caliente al freír. Mantener los chicos lejos de la sartén.',
  pasos: [
    {
      nroPaso: 1,
      titulo: 'Preparar mezcla',
      desc: 'Mezclar carne, cebolla, ajo opcional, huevo opcional, sal, pimienta y orégano.',
      tiempo: '8 min',
      tiempoMin: 8,
      puntoClave: 'Antes de cocinar.',
      errorComun: 'Usar pan rallado si se busca bajo hidrato.',
    },
    {
      nroPaso: 2,
      titulo: 'Hervir las papas',
      desc: 'Pelar y cortar en cubos grandes. Poner en agua fría con sal, llevar a hervor.',
      tiempo: '20 min',
      tiempoMin: 20,
      puntoClave: 'Arrancar con agua FRÍA, no caliente — cocina más parejo.',
      errorComun: 'No compactar demasiado; dorar antes de salsa; controlar que no se seque.',
      notas: 'Si querés más livianas, hervilas en vez de freírlas.',
    },
    {
      nroPaso: 3,
      titulo: 'Precalentar aceite',
      desc: 'Sartén grande con 1 cm de aceite. Calor medio-alto. Probar con una miga: tiene que dorar en 5 segundos.',
      tiempo: '5 min',
      tiempoMin: 5,
      errorComun: 'Si humea el aceite, está demasiado caliente — bajá la hornalla.',
    },
    {
      nroPaso: 4,
      titulo: 'Freír las milanesas',
      desc: '3 minutos por lado o hasta dorado. No amontonar — de a 2 por vez. Escurrir sobre papel absorbente.',
      tiempo: '12 min',
      tiempoMin: 6,
      puntoClave: 'Si no chisporrotea al entrar, sacala y esperá.',
    },
    {
      nroPaso: 5,
      titulo: 'Hacer el puré',
      desc: 'Colar las papas. Pisar con la manteca y agregar leche tibia de a poco. Sal a gusto.',
      tiempo: '5 min',
      tiempoMin: 0,
      notas: 'Leche tibia, no fría — emulsiona mejor.',
    },
    {
      nroPaso: 6,
      titulo: 'Emplatar',
      desc: 'Puré en la base, milanesa encima. Si querés, un gajo de limón al costado.',
      tiempo: '2 min',
      tiempoMin: 0,
    },
    {
      nroPaso: 7,
      titulo: 'Avisar a la familia',
      desc: 'A comer 🍽',
      tiempo: '',
      tiempoMin: 0,
    },
  ],
};
